networks:
  majsoul-network:
    driver: bridge

services:
  akagi:
    image: arthals/majsoul-helper:latest 
    container_name: akagi
    ports:
      - "8765:8765"
    volumes:
      - ./app/mitm:/root/.mitmproxy
      - ./app/akagi/logs:/app/Akagi/logs
    networks:
      - majsoul-network
    command: ["akagi"]

  majsoulmax:
    image: arthals/majsoul-helper:latest
    container_name: majsoulmax
    ports:
      - "23410:23410"
    volumes:
      - ./app/mitm:/root/.mitmproxy
      - ./app/majsoulmax/config:/app/MajsoulMax/config
      - majsoulmax_proto:/app/MajsoulMax/proto
    depends_on:
      - akagi
    networks:
      - majsoul-network
    environment:
      - PROXY_USERNAME=arthals
      - PROXY_PASSWORD=WUHzVoKE7mPbBmfU
      # 如果你需要借助 clash 链接 GitHub 更新依赖，开启
      # - http_proxy=http://172.17.0.1:7890
      # - https_proxy=http://172.17.0.1:7890
    # command: ["sleep", "infinity"]
    command: ["majsoulmax"]
  
  frontend:
    image: arthals/majsoul-helper-frontend:latest
    container_name: frontend
    ports:
      - "4173:4173"
# 持久化，避免 config 记录的 proto 版本和实际不一致
volumes:
  majsoulmax_proto: