name: Build Docker Images

on:
  push:
    branches:
      - main   # 推送到 main 分支时触发
  workflow_dispatch:   # 支持手动触发

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build frontend image
        run: |
          docker build -t arthals/majsoul-helper-frontend \
            -f docker/Dockerfile.frontend .

      - name: Build backend image
        run: |
          docker build -t arthals/majsoul-helper \
            -f docker/Dockerfile .
